.Dd November 14, 2024
.Dt BUGS 7
.Os
.Sh NAME
.Nm bugs
.Nd introduction to filing a problem report (PR)
.Sh DESCRIPTION
.Fx
has a centralized repository for tracking problem reports.
A problem report, or PR, can be about any component of FreeBSD,
including problems with the operating system programs,
a mistake in the documentation,
or a new feature that the submitter wishes to see incorporated.
.Pp
Please search for an existing issue before filing a new bug report.
.Sh SEE ALSO
.Lk https://bugs.freebsd.org/ "The FreeBSD Bug Tracker"
.Pp
.Lk https://bugs.freebsd.org/search/ "Search Problem Reports"
.Pp
.Lk https://docs.freebsd.org/en/articles/problem-reports/ "Writing Problem Reports"
.Sh HISTORY
The
.Nm
manual page first appeared in
.Fx 15.0 .
.Sh CAVEATS
Do not include sensitive information in bug reports.
